src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Future__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed By Future</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactsFutureUnsyncerTest.cls
@IsTest
private class ContactsFutureUnsyncerTest {

    @IsTest
    static void unsyncAndProcessContactsRelatedToAccountWithBillingAddress() {
        AccountTestDataFactory.insertAccountsWithOneContactAndBillingAddresses(
                ContactsFutureUnsyncer.ACCOUNTS_TO_SELECT_LIMIT, true, false);

        Test.startTest();
        ContactsFutureUnsyncer.unsyncAndProcessContactsRelatedToAccountWithBillingAddress();
        Test.stopTest();

        List<Contact> contacts = [
                SELECT Id
                FROM Contact
                WHERE Is_Synced__c = FALSE AND Processed_By_Future__c = TRUE
        ];

        System.assert(contacts.size() == ContactsFutureUnsyncer.ACCOUNTS_TO_SELECT_LIMIT);
    }
}